### ISSUE TITLE
Bottleneck: pow

### ISSUE THREAD

**Issue by leahneukirchen** [jibsen/lzdatagen#1]
Hi, I tried generating big outputs from your tool, and 90% of cpu time is spent on pow(3)... it's probably reasonable to precompute the exponential distribution, use a faster sampling method, or simply a less precise version of pow(3) such as https://martin.ankerl.com/2012/01/25/optimized-approximative-pow-in-c-and-cpp/

**Comment by jibsen** [comment]
Hi!

Thanks you for pointing this out (and the excellent suggestions), I'll have a look.

**Comment by jibsen** [comment]
Sidetracked by another project!

I tried the fastPow method you linked, and it was substantially faster
~~~sh
$ time ./lzdgen -s 1g - > /dev/null

real    0m15.549s
user    0m15.545s
sys     0m0.000s

$ time ./lzdgen_fastPow -s 1g - > /dev/null

real    0m3.052s
user    0m3.047s
sys     0m0.000s
~~~

however it is also quite imprecise, which can result in _choppy_ literal distributions. Here are histograms for 1 MiB of `lzdgen -l 1.3 -m 1.0 -r 1.0`

![histograms](https://github.com/jibsen/lzdatagen/assets/1367512/5b6a9909-57ec-41e4-8d50-2192e0f85f3e)

So I've played around with two other ideas. One was to simply replace pow with powf, this resulted in an almost 2x speedup without affecting the literal distribution noticably.

~~~sh
$ time ./lzdgen_powf -s 1g - > /dev/null

real    0m8.431s
user    0m8.414s
sys     0m0.010s
~~~

The second was to pre-generate a sample of literals following the desired distribution and then selecting randomly from that. This is also less precise, but as you can see from the histograms above (the bulk version), it is less choppy.

~~~sh
$ time ./lzdgen_bulk -b -s 1g - > /dev/null

real    0m2.202s
user    0m2.178s
sys     0m0.020s
~~~

The bulk method is available in the [staging branch](https://github.com/jibsen/lzdatagen/tree/staging) if you would like to check it out.

**Comment by leahneukirchen** [comment]
I got sidetracked as well, but this looks pretty okay.  I didn't expect fastPow to be so bad. :D

**Comment by jibsen** [comment]
Merged now, thanks again for raising the issue!
